version=2.6.1+26.3
group=com.khazoda.plushables
license=GPLv3
#
minecraft_version=26.3
minecraft_version_range=[26.3, 26.4)
#
mod_name=Plushables
mod_author=khazoda
mod_id=plushables
#
description=cute plushies for your home
mod_homepage=https://khazoda.com#plushables
mod_sources=https://github.com/khazoda-mods/plushables
mod_issues=https://github.com/khazoda-mods/plushables/issues
# https://fabricmc.net/develop/
fabric_version=0.161.0+26.3
fabric_loader_version=0.19.5
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.3-1
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.3.0.45-beta
neoforge_loader_version_range=[4,)
#
khazodacore_version=1.0.4+26.3
#
java_version=25
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false