version=2.6.1+26.3
group=com.khazoda.plushables
license=GPLv3
#
minecraft_version=26.1
minecraft_version_range=[26.1, 26.2)
#
mod_name=Plushables
mod_author=khazoda
mod_id=plushables
#
description=cute plushies for your home
mod_homepage=https://khazoda.com#plushables
mod_sources=https://github.com/khazoda-mods/plushables
mod_issues=https://github.com/khazoda-mods/plushables/issues
# https://fabricmc.net/develop/
fabric_version=0.145.1+26.1
fabric_loader_version=0.19.3
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[4,)
#
khazodacore_version=1.0.3+26.1
#
java_version=25
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false